### ISSUE TITLE
Simplify install of RSparkling

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/rsparkling#37]
* It would be great to simplify install of rsparkling (proper h2o version + compatible sparkling water version) cc @javierluraschi @mmalohlava @jakubhava

**Comment by javierluraschi** [comment]
Hi @navdeep-G, related to this work: I think it would be great if you could send us a PR to update the `rsparkling` section in our `README`, mostly with the purpose of removing `strict_version_check = FALSE`.

Notice that we just changed the `README` to use Spark 2.1 so I'm hoping that maybe that could allow us to simplify `rsparkling`'s config. My goal is to have fewer lines with this change in the README since it's meant to be a quick/friendly start guide to help users get started; more advanced users would go to `spark.rstudio.com` and `rsparkling`'s `README` as well, in which we can add additional details and caveats if needed. Cheers!

**Comment by navdeep-G** [comment]
Hi @javierluraschi,

The solution is not as trivial as one might think. I will try to come up with a solution soon.

Thanks,
Navdeep

**Comment by jakubhava** [comment]
Maybe this helps - https://github.com/h2oai/rsparkling/pull/76 it will always fetch the correct latest available Sparkling Water

**Comment by jakubhava** [comment]
Already implemented. The next stage is to make release of RSparkling as part of Sparkling Water pipeline
