### ISSUE TITLE
rsparkling weird connection to amazon? 

### ISSUE THREAD

**Issue by randomgambit** [h2oai/rsparkling#39]
Hello there,

Thanks for this amazing package. I have a HPC cluster with Spark and Sparkling Water installed. I am running the simple code:

```
library('sparklyr')
library('dplyr')
library('rsparkling')

Sys.setenv(SPARK_HOME="mypath/spark-2.0.2-bin-hadoop2.6/") 
sc <- spark_connect(master = "spark://node1234:7077")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") : unable to connect to 's3.amazonaws.com' on port 80.
```

Why does `rsparkling` need to connect to amazon at all? I am behind a firewall so this is not possible.
Any ideas?

Thanks!

**Comment by navdeep-G** [comment]
Hi @randomgambit ,

You are seeing this error because you are behind a firewall. `rsparkling` needs access to aws to fetch sparkling water dependencies. See `package.R` in the `rsparkling` repo. Your best solution to this is to follow these guidelines: 

1. https://github.com/h2oai/rsparkling#note-the-previous-command-requires-access-to-the-internet
2.https://github.com/h2oai/rsparkling#note-the-previous-command-requires-access-to-the-internet-1
3.https://github.com/h2oai/rsparkling#note-the-previous-command-requires-access-to-the-internet-2

Please let me know if you have anymore questions.

Cheers,
Navdeep

**Comment by randomgambit** [comment]
great thanks!
